#!/bin/bash
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 10 --suffix ""
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 50  --suffix ""
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 100 --suffix ""
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 200  --suffix ""
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 500 --suffix ""
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 1000 --suffix ""
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 2000 --suffix ""
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9 --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 10000 --suffix ""
#LowMET
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 10 --suffix "_LowMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 50 --suffix "_LowMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 100 --suffix "_LowMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 200 --suffix "_LowMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 500 --suffix "_LowMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 1000 --suffix "_LowMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 2000 --suffix "_LowMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_LowMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 10000 --suffix "_LowMET"



#HighMET
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 10 --suffix "_HighMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 50 --suffix "_HighMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 100 --suffix "_HighMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 200 --suffix "_HighMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 500 --suffix "_HighMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 1000 --suffix "_HighMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 2000 --suffix "_HighMET"
./limit_plots_MonoHgg_ZpBaryonic.py --do-limits -M Asymptotic --input-dir ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET -O ~/www/plotsMonoH/FitLimits/ntuples4fit_pho_met0_met130_cic_default_shapes_lumi_35.9_HighMET --label MonoHgg_ZpBaryonic --lumi 35.9 --use-fb --load lumi_limits.json --mZP 10000 --suffix "_HighMET"
   
   
